### ISSUE TITLE
Add the option to share with everyone (publish)

### ISSUE THREAD

**Issue by pastewka** [ComputationalMechanics/TopoBank#317] opened 2019-07-18 19:38 UTC
This is publishing the dataset

**Comment by pastewka** [comment] 2020-07-07 08:48
Note that when sharing with everyone we also need the option to specify a license

**Comment by mcrot** [comment] 2020-07-08 08:46
Following to [this Wikipedia article](https://de.wikipedia.org/wiki/Open_Data_Commons#Lizenzen), we could offer three
options or choosing a license:

- **CC0**: No copyright, no attribution needed, no share-alike (new work must have same license)
- **CC BY**: Attribution needed, but no share-alike
- **CC BY-SA**: Attribution and share-alike needed

Would this be enough for the start?

**Comment by mcrot** [comment] 2020-07-08 08:56
As alternative, we could use the licenses from the Open Data Commons, which are similar to the CC licenses.
They are very similar, is seems like the CC licences also apply for other contents than data:

https://opendefinition.org/licenses/

Since we have also descriptions of the surfaces/topographies which have been entered by the user, the CC licences may be better here, I think.

**Comment by pastewka** [comment] 2020-07-08 09:54
Let's use CC licenses.

**Comment by pastewka** [comment] 2020-07-08 09:54
And yes, the three you suggested should be sufficient.

**Comment by mcrot** [comment] 2020-07-08 13:17
This is a duplicate of #55 and #179, but we continue here.

**Comment by mcrot** [comment] 2020-07-10 15:12
@pastewka , @AntoineSIMTEK , I've built a "publication form" for the surface. It should clearly inform
the user about 

- the meaning of publication,
- the implications of it,
- and the alternative (sharing).

Afterwards the license is chosen and the user must acknowledge, that he has understood everything and does not want
to change the surface anymore. Here is a screenshot:

![grafik](https://user-images.githubusercontent.com/9113541/87169159-db362900-c2cf-11ea-8609-0c78ed834aab.png)

There are external links to an informal description of the licenses and the legal text.
What do you think about it? Is it comprehensive and understandable?

**Comment by mcrot** [comment] 2020-07-10 15:18
Additionally we have to think about, what to do if the capabilities of a surface or topography are enhanced, e.g.
by an additional property like the tip radius. What to do then with all the published ("freezed") surfaces?
Shall they show a default value for the new field? It it needed to hide new capabilities for those surfaces or topographies?

This would mean that I need to keep track, which surface was published in which version .. that would become a bit complicated.
I'll think about it and then I would like to discuss that with you, @pastewka and @AntoineSIMTEK .

**Comment by AntoineSIMTEK** [comment] 2020-07-10 15:21
"You also allow other users to do so, if you want": did you mean "You can also allow other users to do so, if you want"

"All users will be notifierd about this publication along with a link". Do you mean this will appear in the bell for everyone ?

**Comment by AntoineSIMTEK** [comment] 2020-07-10 15:23
I like your description otherwise. It is clear and easy to read.

**Comment by mcrot** [comment] 2020-07-10 15:30
> "You also allow other users to do so, if you want": did you mean "You can also allow other users to do so, if you want"

Yes, thank you!

> "All users will be notifierd about this publication along with a link". Do you mean this will appear in the bell for everyone ?

Yes, this is my idea. Do you think, it's useful?

**Comment by pastewka** [comment] 2020-07-10 15:36
Rather "You cannot ... any more" -> "You can no longer". Otherwise good. I'd like to invite @tdbjacobs to look at this!

**Comment by mcrot** [comment] 2020-07-15 10:11
The publishing has been implemented in my development branch. The publication form now looks like this:
![grafik](https://user-images.githubusercontent.com/9113541/87533000-41d29280-c694-11ea-80ee-517fc038b6cb.png)

@tdbjacobs , what do you think about this form?

**Comment by mcrot** [comment] 2020-07-15 10:34
While working on the publication feature, I've found that we also have to think about the implications of publication on development.

Once the users can publish, they cannot change any properties of a surface and the belonging topographies (description, tags, flags, sizes, units, ..). How should we handle this from the perspective of further development?

First:  It's not possible to remove properties from the underlying model, which is okay. So every future surface needs to have
a name, a creator, a category and a description. Every future topography also needs a measurement_date. We
cannot remove the date from the model. So far every topography needs a measurement date.
Also the change of data types of existing properties maybe difficult (like using a timestamp instead of a date).

These implications are okay, I think - we just may consider whether we want the *measurement date being mandatory*.

But **what about adding new properties or new features to surfaces and topographies**, e.g. a tip radius, to the database model?
Up to now, each surface and topography correspond to a row in a table, which columns represent the properties.

So if we add a new column, also the old and published surfaces and topographies will have that new column. We would need
default values for that columns (could be NULL=nothing, if feasible).

These new properties also cause new UI elements, like showing the value of such property. And maybe new logic.
The visual representation of the published items may change, because it depends on the same code for all items.

Suggestion:

- We could add all new properties as NULL values and handle these values
  in the UI in a special way. Or if a NULL value is not feasible, we provide another default.
- We include a statement in the publication form, that new properties may be added which do not affect the existing data?
- We review the existing properties, including `measurement_date`

If you have any thoughts on this, @pastewka , @AntoineSIMTEK , @tdbjacobs , let me know.
I would like to clarify this because the publication feature is online.

Probably it is easier to discuss that in a video conference.

**Comment by mcrot** [comment] 2020-07-15 10:47
Another idea: The publication only refers to a subset of the data, the raw files and maybe some properties.
The parts which have not been published can still change as the UI or the representation in the database may change in future.

This should be clearly stated in the publication form (what is published eventually?).

**Comment by tdbjacobs** [comment] 2020-07-15 13:59
Thanks to Lars for bringing my attention to this comment. Here are my thoughts:
	1.	I’m not sure it’s necessary to notify every user every time a surface is published. 
	⁃	Perhaps instead, we can have an easy way for any user to click through to browse the library of published surfaces. 
	2.	Does the published surface get a DOI? (I think it needs to!)
	3.	In the “Implications of publishing”, most of these sound like disadvantages of publishing. 
	⁃	We need to be sure to acknowledge the benefits of publishing (DOI, archivability, citability, open data, etc., etc.)
	4.	We should include a suggested way of citing a surface here. 
	⁃	We can look at other data repositories and see how they suggest citation. It would be useful to give an example citation for people to follow would be useful. 
	5.	Are there ways to create subsequent versions of the published surface? 
	⁃	(even arXiv lets you upload a revised version and, while the old one is never taken down, the viewer can see the whole version history. (This allows correction of mistakes, and makes it feel less scary to publish))
	6.	Is there a way to create a duplicate of the surface so that the user can publish one copy and keep working with the other copy? 
	⁃	Here’s a use case: Abhijeet has done a huge amount of work on UNCD. We wish to publish that data to connect it to his published paper. But we may also add additional measurements of UNCD taken by future students - potentially using additional techniques. Therefore, I don’t want to feel that I’m “losing” that surface forever. Just “archiving” a time-stamped copy of it. 
	7.	In box two, change “Consider the alternative: Sharing” to “Alternative to publication: Sharing”
	8.	In box two, change “You can still remove the share or even the surface later on” to “You retain the ability to disable sharing and/or delete the surface in the future.”
	9.	In box two, I don’t understand the comment “You also allow other users to do so, if you want.”
	⁃	Does that mean that, by sharing, you allow others to edit the surface?
	⁃	Or does that meant that, once you share it, you have a further option to allow/disallow editing by those you share it with? 
	10.	In box three, I recommend a brief description of each license. Many people will wish to choose without clicking through to a full description. 
	11.	In box three, change “No more modifications are required regarding….” to “No more modifications are allowed regarding…”

**Comment by mcrot** [comment] 2020-07-15 15:04
Thanks for your comments, @tdbjacobs . I think they are a good basis for discussion. I've quoted your 
points and replied underneath each one below.

> 1. I’m not sure it’s necessary to notify every user every time a surface is published.
> ⁃ Perhaps instead, we can have an easy way for any user to click through to browse the library of published surfaces.

I'm also not 100% sure, but I thought the notification about published surfaces could encourage people to publish themselves
or to get in contact for collaboration. We could also remove the notification as the user base grows or make it a configuration option for each user. But if there is no point in notification from the beginning, I can also remove it now.

Regarding an easy way to browse all published surfaces: This is implemented in my development version as
extra filter on the "Select" tab:

![only-published-filter](https://user-images.githubusercontent.com/9113541/87556358-d6e68300-c6b6-11ea-9aed-fbaad0ea22d5.png)


> 2. Does the published surface get a DOI? (I think it needs to!)

So far not. We've planned that for a later release (https://github.com/ComputationalMechanics/TopoBank/issues/301)
because we haven't finally decided how to get a DOI. An easy option would be to use a platform like [figshare](https://figshare.com/), e.g. by uploading the surface's ZIP file including a URL pointing to "contact.engineering", but then the data is published officially there.

> 3. In the “Implications of publishing”, most of these sound like disadvantages of publishing.
> ⁃ We need to be sure to acknowledge the benefits of publishing (DOI, archivability, citability, open data, etc., etc.)

Yes, we could make a pro & contra list there for example. However, DOI and citability is not implemented yet.

> 4. We should include a suggested way of citing a surface here.
> ⁃ We can look at other data repositories and see how they suggest citation. It would be useful to give an example citation for people to follow would be useful.

So far you can refer to the surfaces by URL, but that URL is not yet permanent, so I think that is not enough. 
For citability, yes, we should look at other data repositories and we need a permanent URL, I guess. 
I've discussed with Lars and something like
```
 https://contact.engineering/publications/<UUID>
```
should do it, where `<UUID>`is a long hexadecimal.

With this, we could show  a pop-up window, with a citation - maybe in different formats. These citations should also
be accessible later.

> 5. Are there ways to create subsequent versions of the published surface?
> ⁃ (even arXiv lets you upload a revised version and, while the old one is never taken down, the viewer can see the whole version history. (This allows correction of mistakes, and makes it feel less scary to publish))

Not yet. This could be also a solution for the implication for further development. 
Yes, would be much less scary. 

> 6. Is there a way to create a duplicate of the surface so that the user can publish one copy and keep working with the other copy?
> ⁃ Here’s a use case: Abhijeet has done a huge amount of work on UNCD. We wish to publish that data to connect it to his published paper. But we may also add additional measurements of UNCD taken by future students - potentially using additional techniques. Therefore, I don’t want to feel that I’m “losing” that surface forever. Just “archiving” a time-stamped copy of it.

I understand your use case. This is not implemented yet. 

Such a duplicate could work like a "fork" in software repositories, where you get a copy which can be changed by yourself.
Maybe later, the user could use it to "replace" the already published version when branded with a new version (e.g. "v2").
This would be a way to handle your point 5.

> 7. In box two, change “Consider the alternative: Sharing” to “Alternative to publication: Sharing”
> 8. In box two, change “You can still remove the share or even the surface later on” to “You retain the ability to disable sharing and/or delete the surface in the future.”

Both changed, thanks.

> 9. In box two, I don’t understand the comment “You also allow other users to do so, if you want.”
> ⁃ Does that mean that, by sharing, you allow others to edit the surface?
> ⁃ Or does that meant that, once you share it, you have a further option to allow/disallow editing by those you share it with?

The second option, yes. This has been implemented earlier with sharing, it's online. Here is a screenshot of the dialog:

![grafik](https://user-images.githubusercontent.com/9113541/87559995-45c5db00-c6bb-11ea-8889-18fc19dd4b65.png)

By pressing "Allow change", others can change the surface.

> 10. In box three, I recommend a brief description of each license. Many people will wish to choose without clicking through to a full description.

I thought about it before and I think I would have to add a note, that these descriptions are
not legally binding. That can added of course.

> 11. In box three, change “No more modifications are required regarding….” to “No more modifications are allowed regarding…”

Changed.

**Comment by pastewka** [comment] 2020-07-17 07:15
Here is my take on this.

> > 1. I’m not sure it’s necessary to notify every user every time a surface is published.
> >    ⁃ Perhaps instead, we can have an easy way for any user to click through to browse the library of published surfaces.
> 
> I'm also not 100% sure, but I thought the notification about published surfaces could encourage people to publish themselves
> or to get in contact for collaboration. We could also remove the notification as the user base grows or make it a configuration option for each user. But if there is no point in notification from the beginning, I can also remove it now.

Do not notify users about published surfaces. This gets annoying quickly.

> > 1. Does the published surface get a DOI? (I think it needs to!)
> 
> So far not. We've planned that for a later release (#301)
> because we haven't finally decided how to get a DOI. An easy option would be to use a platform like [figshare](https://figshare.com/), e.g. by uploading the surface's ZIP file including a URL pointing to "contact.engineering", but then the data is published officially there.

We cannot get a DOI because we have to pay for DOIs. There is no way that I see at present to finance this. Also, there are certain requirements as to how long the DOI remains active.

I would opt for designing our own qualifier. The simplest would be a UUID. My suggestion is anyway to identify surfaces by UUID only, i.e. redesign the internal reference to the surface that is currently a consecutive index. We had discussed this before. The UUID is then the permanent marker of the surface. I'd suggest to introduce permalink of the form

https://contact.engineering/go/<UUID>

or similar that remains active even if the change the underlying API.
> > 1. In the “Implications of publishing”, most of these sound like disadvantages of publishing.
> >    ⁃ We need to be sure to acknowledge the benefits of publishing (DOI, archivability, citability, open data, etc., etc.)
> 
> Yes, we could make a pro & contra list there for example. However, DOI and citability is not implemented yet.

We should not make it sound like a disadvantage. We do not need a pro and contra list. This reminds me a bit of the scene in "The Truman Show" where he goes into a travel agency and there is a poster in the background with a plane and a lightning through the wing.
> > 1. We should include a suggested way of citing a surface here.
> >    ⁃ We can look at other data repositories and see how they suggest citation. It would be useful to give an example citation for people to follow would be useful.
> 
> So far you can refer to the surfaces by URL, but that URL is not yet permanent, so I think that is not enough.
> For citability, yes, we should look at other data repositories and we need a permanent URL, I guess.
> I've discussed with Lars and something like
> 
> ```
>  https://contact.engineering/publications/<UUID>
> ```

Yes, citation should be via URL. If would prefer something shorter than 'publications', see my suggestion above.
> should do it, where `<UUID>`is a long hexadecimal.
> 
> With this, we could show a pop-up window, with a citation - maybe in different formats. These citations should also
> be accessible later.

This should be accessible somewhere on the properties page of the surface. We could add a tab "how to cite".
> > 1. Are there ways to create subsequent versions of the published surface?
> >    ⁃ (even arXiv lets you upload a revised version and, while the old one is never taken down, the viewer can see the whole version history. (This allows correction of mistakes, and makes it feel less scary to publish))
> 
> Not yet. This could be also a solution for the implication for further development.
> Yes, would be much less scary.

This is a great idea. We absolutely need the possibility to update a surface and publish an updated version. 

> > 1. Is there a way to create a duplicate of the surface so that the user can publish one copy and keep working with the other copy?
> >    ⁃ Here’s a use case: Abhijeet has done a huge amount of work on UNCD. We wish to publish that data to connect it to his published paper. But we may also add additional measurements of UNCD taken by future students - potentially using additional techniques. Therefore, I don’t want to feel that I’m “losing” that surface forever. Just “archiving” a time-stamped copy of it.
> 
> I understand your use case. This is not implemented yet.
> 
> Such a duplicate could work like a "fork" in software repositories, where you get a copy which can be changed by yourself.
> Maybe later, the user could use it to "replace" the already published version when branded with a new version (e.g. "v2").
> This would be a way to handle your point 5.

I agree. This should be handled like a fork where the link to the original (published or unpublished) surface remains in our database. A question would be whether we need a way to break that link.

> > 1. In box two, change “Consider the alternative: Sharing” to “Alternative to publication: Sharing”
> > 2. In box two, change “You can still remove the share or even the surface later on” to “You retain the ability to disable sharing and/or delete the surface in the future.”

Agreed.

> > 1. In box three, I recommend a brief description of each license. Many people will wish to choose without clicking through to a full description.
> 
> I thought about it before and I think I would have to add a note, that these descriptions are
> not legally binding. That can added of course.

Agreed.

**Comment by mcrot** [comment] 2020-07-17 13:14
> Do not notify users about published surfaces. This gets annoying quickly.

Okay, removed.

> I would opt for designing our own qualifier. The simplest would be a UUID. My suggestion is anyway to identify surfaces by UUID only, i.e. redesign the internal reference to the surface that is currently a consecutive index. We had discussed this before. The UUID is then the permanent marker of the surface. I'd suggest to introduce permalink of the form
> 
> ```
> https://contact.engineering/go/<UUID>
> ```
> 
> (@mcrot also suggested this, see below)
> 
> or similar that remains active even if we change the underlying API.

Okay, agreed on the URL. Now I think we'll need such an URL already from the beginning.

> > Yes, we could make a pro & contra list there for example. However, DOI and citability is not implemented yet.
> 
> We should not make it sound like a disadvantage. We do not need a pro and contra list. This reminds me a bit of the scene in "The Truman Show" where he goes into a travel agency and there is a poster in the background with a plane and a lightning through the wing.

Well, our plane would still have the positive aspect of still reaching its destination, not a total desaster :wink: 

Okay - with the new idea of versioning, it will be easier to focus on the benefits. However,
the "disadvantages" should still be mentioned I think. We should avoid the situation in which users insist
on reverting a publication because they didn't know. 

> Yes, citation should be via URL. If would prefer something shorter than 'publications', see my suggestion above.

Yes, I like "go" instead - it could also be used for other purposes later. 

> This should be accessible somewhere on the properties page of the surface. We could add a tab "how to cite".

Good idea.

> This is a great idea. We absolutely need the possibility to update a surface and publish an updated version.

Yes, this solves several problems.

> > > 1. Is there a way to create a duplicate of the surface so that the user can publish one copy and keep working with the other copy?
> > Such a duplicate could work like a "fork" in software repositories, where you get a copy which can be changed by yourself.
> > Maybe later, the user could use it to "replace" the already published version when branded with a new version (e.g. "v2").
> > This would be a way to handle your point 5.
> 
> I agree. This should be handled like a fork where the link to the original (published or unpublished) surface remains in our database. A question would be whether we need a way to break that link.

Okay, I'll probably implement this by an additional field for surfaces: The ID of the surface it originates from.

Thank you @tdbjacobs and @pastewka , now it is much more clear. I'll prepare an update and let you know when
I have an update, e.g. for the publication form. Let me know if you have more suggestions or comments.

**Comment by pastewka** [comment] 2020-07-17 13:50
> > > Yes, we could make a pro & contra list there for example. However, DOI and citability is not implemented yet.
> > 
> > 
> > We should not make it sound like a disadvantage. We do not need a pro and contra list. This reminds me a bit of the scene in "The Truman Show" where he goes into a travel agency and there is a poster in the background with a plane and a lightning through the wing.
> 
> Well, our plane would still have the positive aspect of still reaching its destination, not a total desaster 😉
> 
> Okay - with the new idea of versioning, it will be easier to focus on the benefits. However,
> the "disadvantages" should still be mentioned I think. We should avoid the situation in which users insist
> on reverting a publication because they didn't know.

Yes, that is right. We should clearly state that the surface becomes accessible to everyone and that there is no way to revert this choice.

> Thank you @tdbjacobs and @pastewka , now it is much more clear. I'll prepare an update and let you know when
> I have an update, e.g. for the publication form. Let me know if you have more suggestions or comments.

Sounds good, and thanks for implementing this!

**Comment by mcrot** [comment] 2020-07-20 09:38
One more question, just to be sure: For each version of a surface, a *new permanent URL* should be created, right? 
A citation should always refer to a specific version of the data, correct?

I've had a look a "Zenodo", who [always provide two DOIs for a new publication](https://help.zenodo.org/#versioning) :

- one for the specific version
- one for the full history of a dataset

The same could be interesting for us, e.g. by providing two "go" URLs.

**Comment by pastewka** [comment] 2020-07-20 09:44
That would be an idea. However, I think that only the specific version would be sufficient since this is what you want to cite. The surface should then have a tab pointing out older and newer versions.

**Comment by mcrot** [comment] 2020-07-20 10:15
Okay, thanks! So the system will still have all versions of a surface. 

This brings up the question, which versions should be listed by default on the "Select" tab. I think a good default is to show only the latest versions while providing an additional checkbox "[x] Show all published versions".

**Comment by pastewka** [comment] 2020-07-20 10:17
I would just show the latest version. There could be a drop down box in this list (and in the properties panel) that allows to select a different version, if there are multiple.

**Comment by mcrot** [comment] 2020-07-24 08:23
Currently I'm not sure whether we really need UUIDs in the URL for the publication. They are easy to generate, that's good.

On the other hand, they are quite long and if the URL is printed somewhere, one has to type a lot of characters. An alternative would be to use a strategy as URL shorteners do. A URL like `https://contact.engineering/go/e5dej4` is probably more handy.
We could start with a length of 5, e.g. and increase the length later, when needed. What do you think?

**Comment by pastewka** [comment] 2020-07-24 13:32
Sounds good. I agree that UUIDs are clumsy, these shortened URLs look better.

**Comment by mcrot** [comment] 2020-08-24 16:51
I'm currently implementing an additional tab on the surface's property page named "how to cite".

As possible form for a citation, I've found the following:  https://libguides.lib.msu.edu/c.php?g=96245&p=626239
Here this format is proposed, named "APA style"

> Author/Rightsholder. (Year). Title of data set (Version number) [Description of form]. Retrieved from http:// 

Here an example, how this looks like in the web app. Let me know what you think, @pastewka, @tdbjacobs , @AntoineSIMTEK :

![grafik](https://user-images.githubusercontent.com/9113541/91072688-2915af00-e63a-11ea-8baa-a6884264118f.png)

The "localhost" link will be a link to our website instead, of course, like `https://contact.engineering/go/b4tc8`.
About the "Description of form" I'm not sure. The example say e.g. "data file" if the data file is referenced by the URL.
We want to reference the URL in the web app,  as far as I understood.

Additionally we could offer import files for common citation managers (BibTeX, ..?)

**Comment by tdbjacobs** [comment] 2020-08-24 17:44
It seems to me the most important thing is that, if we are inventing a new
type of data format, then we need to somehow describe it (briefly) in the
citation. For instance: "Multiple topography measurements of a single
surface" "Container of topography data" or something else.



Tevis Jacobs
Assistant Professor
Mechanical Engineering and Materials Science
University of Pittsburgh
http://www.engineering.pitt.edu/JacobsLab/
Mail: 636 Benedum Hall, 3700 O'Hara St., Pittsburgh, PA 15261
Office: 538-E Benedum Hall, 412-624-9736
tjacobs@pitt.edu

**Comment by mcrot** [comment] 2020-08-25 07:46
In my opinion, this depends on the kind of object, the URL points to.
So far it is planned that the URL of the publication points to the website
of the surface inside the application. The users then see the topographies
and can download data if they wish, but it is not automatically downloaded.

If the URL in the publication points to the data container (which you would also get
by pressing the "download" button"), then we should mention that type of format in the citation 
("Container of topography data" or similar), I agree.

@tdbjacobs , do you think, we should publish a link to the data container, not to the website?
The users wouldn't see our application then. 

I like the first alternative more, because the visitors may open an account and use it, too.

**Comment by mcrot** [comment] 2020-08-25 09:34
In addition - I've found more examples here: https://www.mendeley.com/guides/web-citation-guide

Here, for the citation of the website, the format was left out. Additionally the name of the website is mentioned ("contact.engineering"). This is better, I think:
![grafik](https://user-images.githubusercontent.com/9113541/91158061-6aec3700-e6c6-11ea-98f9-dcd6aa8d6a86.png)

Although, with the name of the website ("contact.engineering") it is a little confusing, that it introduces an extra dot in the line.

**Comment by mcrot** [comment] 2020-08-25 09:46
Let's also discuss the style of author names, maybe after agreeing on the other parts. We could also include the ORCID iD of the author, e.g. as icon with a link for a citation in HTML.

**Comment by tdbjacobs** [comment] 2020-08-25 20:54
No, you're probably right. Probably better to have them go to our website.
Should link to that.

-Tevis


Tevis Jacobs
Assistant Professor
Mechanical Engineering and Materials Science
University of Pittsburgh
http://www.engineering.pitt.edu/JacobsLab/
Mail: 636 Benedum Hall, 3700 O'Hara St., Pittsburgh, PA 15261
Office: 538-E Benedum Hall, 412-624-9736
tjacobs@pitt.edu

**Comment by mcrot** [comment] 2020-08-31 12:59
I've implemented most of the changes as discussed here. The following publication form reflect those changes:

![image](https://user-images.githubusercontent.com/9113541/91722046-fddf1280-eb99-11ea-9572-0bd7c74fc44f.png)

I think, it's not scary any more. What do think about it, @pastewka, @AntoineSIMTEK , @tdbjacobs ?

**Comment by pastewka** [comment] 2020-08-31 13:18
Looks good. Minor wording changes: "another version" to "an updated version". The first check box under "Final checks" is a little confusing. Maybe something like "I attest that the Topography data and its metadata is complete." Is that what you mean?

**Comment by mcrot** [comment] 2020-08-31 13:52
Yes, I meant, that it is complete. I'll change both, thanks. 

Do we also need a checkbox in order to ensure that the publisher is really the copyright owner?
For example, if someone uploads topography data from NASA (hgt) and presses "Publish"?

**Comment by pastewka** [comment] 2020-08-31 14:02
Yes, I think a box saying "I hold copyright of this data or have been authorized by the copyright holders." would be useful.



________________________________
Von: Michael Röttger <notifications@github.com>
Gesendet: Montag, 31. August 2020 15:53
An: ComputationalMechanics/TopoBank
Cc: Lars Pastewka; Mention
Betreff: Re: [ComputationalMechanics/TopoBank] Add the option to share with everyone (publish) (#317)

**Closed** 2020-09-16 13:04 UTC
Labels: enhancement
