### ISSUE TITLE
Load error!

### ISSUE THREAD

**Issue by tdbjacobs** [ComputationalMechanics/TopoBank#556] opened 2020-11-24 15:43 UTC
When I search for anything in my Surfaces tab, I get a Load error! 

See screenshot. 
<img width="2560" alt="Screen Shot 2020-11-24 at 10 41 34 AM" src="https://user-images.githubusercontent.com/22891610/100116548-dec2ea80-2e41-11eb-953c-228854970844.png">

**Comment by mcrot** [comment] 2020-11-24 16:50
@tdbjacobs , it hard to reproduce this for me, it works in my Chrome and Firefox browser. Which Chrome version do you use?
When this happens, could you open the Console by pressing "Shift+Ctrl+i" and see whether there is any Javascript error message on the right? It should look similar to this:

![grafik](https://user-images.githubusercontent.com/9113541/100125837-83aee900-2e7d-11eb-85cf-ba0fdfe62443.png)

This is a duplicate of #543 .

**Comment by mcrot** [comment] 2020-11-25 09:56
Additionally: It would be also interesting to see in the "Network" tab, whether all Javascript components could be loaded.
In order to see this, please open the Console by pressing "Shift+Ctrl+i" (if not already happened), select the "Network" tab and you see this window:
![grafik](https://user-images.githubusercontent.com/9113541/100211451-7260ed80-2f0c-11eb-84ea-c9f8b6b81a22.png)
If you then press "Ctrl+R", the page is reloaded and the table fills with data, e.g.:
![grafik](https://user-images.githubusercontent.com/9113541/100211544-8e648f00-2f0c-11eb-957a-5e0a666a5f15.png)
It would be interesting, if there are any lines where the status code does not show "200" but another number like "404" or "500".

If you could send here screenshots from the "Console" tab and the "Network" tab in case of "Load Error", that would be great
in order to debug this.

**Comment by mcrot** [comment] 2020-12-04 09:22
Okay, now I know how to reproduce it. Since this is duplicate of #543 and there is already some research, I'm closing this.
I'm trying to provide a fix in the next release.

**Closed by mcrot** 2020-12-04 09:22 UTC
